export const SELECT_CREATE_COMPLAIN_IMAGES = 'SELECT_CREATE_COMPLAIN_IMAGES';
export const RESET_ADD_COMPLAIN_PHOTOS = 'RESET_ADD_COMPLAIN_PHOTOS';
export const ADD_COMPLAIN_SPINNER = 'ADD_COMPLAIN_SPINNER';
export const ADD_COMPLAIN_SUCCESS = 'ADD_COMPLAIN_SUCCESS';
export const ADD_COMPLAIN_FAILED = 'ADD_COMPLAIN_FAILED';
