///wait approval
export const APPROVE_SPINNER = 'APPROVE_SPINNER';
export const APPROVE_SUCCESS = 'APPROVE_SUCCESS';
export const APPROVE_FAILED = 'APPROVE_FAILED';

export const REJECT_FAILED = 'REJECT_FAILED';
export const REJECT_SUCCESS = 'REJECT_SUCCESS';
export const REJECT_SPINNER = 'REJECT_SPINNER';
///wait EXCUTION
export const SELECT_EXCUTION_IMAGES = 'SELECT_EXCUTION_IMAGES';
export const EXCUTION_SUCCESS = 'EXCUTION_SUCCESS';
export const EXCUTION_SPINNER = 'EXCUTION_SPINNER';
export const EXCUTION_FAILED = 'EXCUTION_FAILED';
export const CLOSE_EXCUTION_BOTTOM_SHEET = 'CLOSE_EXCUTION_BOTTOM_SHEET';
//solved

//rjected
