export const LOGIN_USER_NAME_CHANGE = 'LOGIN_USER_NAME_CHANGE';
export const LOGIN_USER_PASSWORD_CHANGE = 'LOGIN_USER_PASSWORD_CHANGE';

export const LOGIN_SPINNER = 'LOGIN_SPINNER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
