export const GET_DASHBOARD_DATA_SPINNER = 'GET_DASHBOARD_DATA_SPINNER';
export const GET_DASHBOARD_DATA_SUCCESS = 'GET_DASHBOARD_DATA_SUCCESS';
export const GET_DASHBOARD_DATA_FAILED = 'GET_DASHBOARD_DATA_FAILED';

export const DASHBOARD_FILTER_INPUT_CHANGE = 'DASHBOARD_FILTER_INPUT_CHANGE';
