export const GET_COMPLAINS_LIST_SPINNER = 'GET_COMPLAINS_LIST_SPINNER';
export const GET_COMPLAINS_LIST_SUCCESS = 'GET_COMPLAINS_LIST_SUCCESS';
export const GET_COMPLAINS_LIST_FAILED = 'GET_COMPLAINS_LIST_FAILED';
export const GET_COMPLAINS_LIST_PAGINATION_SPINNER =
   'GET_COMPLAINS_LIST_PAGINATION_SPINNER';
export const GET_COMPLAINS_LIST_PAGINATION_SUCCESS =
   'GET_COMPLAINS_LIST_PAGINATION_SUCCESS';
export const GET_COMPLAINS_LIST_PAGINATION_FAILED =
   'GET_COMPLAINS_LIST_PAGINATION_FAILED';
