export const GET_COMPLAINS_LIST_SPINNER = 'GET_COMPLAINS_LIST_SPINNER';
export const GET_COMPLAINS_LIST_SUCCESS = 'GET_COMPLAINS_LIST_SUCCESS';
export const GET_COMPLAINS_LIST_FAILED = 'GET_COMPLAINS_LIST_FAILED';
export const GET_COMPLAINS_LIST_PAGINATION_SPINNER =
   'GET_COMPLAINS_LIST_PAGINATION_SPINNER';
export const GET_COMPLAINS_LIST_PAGINATION_SUCCESS =
   'GET_COMPLAINS_LIST_PAGINATION_SUCCESS';
export const GET_COMPLAINS_LIST_PAGINATION_FAILED =
   'GET_COMPLAINS_LIST_PAGINATION_FAILED';

export const UNMOUNT_EMPTY = 'UNMOUNT_EMPTY';

export const COMPLAIN_NUMBER_CHANGE = 'COMPLAIN_NUMBER_CHANGE';
export const CONTRUCTOR_ID_CHANGE = 'CONTRUCTOR_ID_CHANGE';
export const COMPLAIN_STATUS_CHANGE = 'COMPLAIN_STATUS_CHANGE';
export const PLATE_NUMBER_CHANGE = 'PLATE_NUMBER_CHANGE';
export const COMPLAIN_TYPE_CHANGE = 'COMPLAIN_TYPE_CHANGE';
export const START_DATE_CHANGE = 'START_DATE_CHANGE';
export const END_DATE_CHANGE = 'END_DATE_CHANGE';
export const RESET_ALL_SEARCH_INPUTS = 'RESET_ALL_SEARCH_INPUTS';

export const SEARCH_SPINNER = 'SEARCH_SPINNER';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILED = 'SEARCH_FAILED';

export const SEARCH_PAGINATION_SPINNER = 'SEARCH_PAGINATION_SPINNER';
export const SEARCH_PAGINATION_SUCCESS = 'SEARCH_PAGINATION_SUCCESS';
export const SEARCH_PAGINATION_FAILED = 'SEARCH_PAGINATION_FAILED';
