export const GET_WAITVIEW_COMPLAINS_SPINNER = ' GET_WAITVIEW_COMPLAINS_SPINNER';

export const GET_WAITVIEW_COMPLAINS_SUCCESS = ' GET_WAITVIEW_COMPLAINS_SUCCESS';

export const GET_WAITVIEW_COMPLAINS_FAILED = ' GET_WAITVIEW_COMPLAINS_FAILED';
