export const GET_SPAREPARTS = ' GET_SPAREPARTS';
export const SELECT_IMAGES_SUCCESS = ' SELECT_IMAGES_SUCCESS';
export const CLOSE_BOTTOM_SHEET = ' CLOSE_BOTTOM_SHEET';
export const IN_GUARANTEE_ITEM_CHECKED = ' IN_GUARANTEE_ITEM_CHECKED';
export const OUT_GUARANTEE_ITEM_CHECKED = ' OUT_GUARANTEE_ITEM_CHECKED';
