export const GET_SPAREPARTS = ' GET_SPAREPARTS';
export const SELECT_IMAGES_SUCCESS = ' SELECT_IMAGES_SUCCESS';
export const CLOSE_BOTTOM_SHEET = ' CLOSE_BOTTOM_SHEET';
export const IN_GUARANTEE_ITEM_CHECKED = ' IN_GUARANTEE_ITEM_CHECKED';
export const OUT_GUARANTEE_ITEM_CHECKED = ' OUT_GUARANTEE_ITEM_CHECKED';

export const PERVIEW_SPINNER = ' PERVIEW_SPINNER';
export const PERVIEW_SUCCESS = ' PERVIEW_SUCCESS';
export const PERVIEW_FAILED = ' PERVIEW_FAILED';
